name: POP_MOC
channels:
    - conda-forge
    - ncar
    - nodefaults
dependencies:
    - bokeh
    - bottleneck
    - cartopy
    - climpred
    - cf-units
    - cftime
    - cmocean
    - dask==2021.9
    - dask-jobqueue
    - distributed==2021.9
    - dask-labextension
    - datashader
    - eofs
    - esmpy
    - geocat-viz
    - geocat-comp
    - geoviews
    - holoviews
    - intake
    - intake-esm
    - ipykernel
    - ipywidgets
    - jupyter-server-proxy
    - jupyterlab
    - matplotlib
    - metpy
    - nc-time-axis
    - netcdf4
    - nodejs
    - numba
    - numpy
    - pandas
    - pint
    - pip
    - pop-tools
    - pre-commit
    - pytest
    - python==3.8
    - scipy
    - seaborn
    - seawater
    - statsmodels
    - toolz
    - tqdm
    - watermark
    - xarray>=0.20.1
    - xesmf # xarray interface it ESMF tools
    - xgcm # General Circulation Model Postprocessing with xarray
    - xhistogram # Fast, flexible, label-aware histograms for numpy and xarray
    - xrft # fourier transforms for xarray data
    - xoak
    - xskillscore>=0.0.23
    - zarr
    - ncar-jobqueue
